In [1]:
#pip install tensorflow-datasets

In [2]:
import tensorflow as tf
import tensorflow_datasets as tfds
mnist_data = tfds.load('fashion_mnist')
for item in mnist_data:
    print(item)

train
test


딕셔너리값 trian, test 출력

그러므로 load 할 때 split을 사용해 따로 가져올 수 있음

In [3]:
mnist_train = tfds.load('fashion_mnist', split='train')
assert isinstance(mnist_train, tf.data.Dataset) # assert는 오른쪽 조건이 맞는지 아닌지 확인(아니면 동작x)
print(type(mnist_train))

<class 'tensorflow.python.data.ops.prefetch_op._PrefetchDataset'>


결과로 PrefetchDataset의 객체가 출력된다. 이 객체를 순회하면서 데이터 조사할 수 있다.

이 클래스의 좋은 기능 하나는 take(1) 메서드를 호출해 첫 번째 레코드를 가져올 수 있다는 것이다.

데이터가 어떻게 들어있는지 확인해보겠다

In [4]:
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())

<class 'dict'>
dict_keys(['image', 'label'])


2024-02-29 14:20:56.284759: W tensorflow/core/kernels/data/cache_dataset_ops.cc:854] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


1. 첫 번쨰 print 문의 출력은 각 레코드의 타입이 딕셔너리라는 것을 보여준다.

2. 이 딕셔너리의 키를 출력하면 image와 label임을 알 수 있다.

따라서 데이터 값을 확인하려면 다음과 같이 쓸 수 있다.

In [5]:
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())
    print(item['image'])
    print(item['label'])

<class 'dict'>
dict_keys(['image', 'label'])
tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]
  [ 74]
  [ 83]
  [ 77]
  [108]
  [ 34]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]


2024-02-29 14:20:56.300906: W tensorflow/core/kernels/data/cache_dataset_ops.cc:854] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


이미지 항목은 tf.Tensor 타입으로 크기가 28x28인 배열이다.

픽셀 강도를 나타내는 0-255 사이의 값이 들어있다.

레이블은 tf.Tensor(2, shape=(), dtype=int64)로 출력되며 해당 이미지가 클래스 2에 해당하는 것을 확인할 수 있다.
        
        

데이터셋을 로드할 때 with_info 매개변수를 사용하면 데이터셋에 대한 정보 얻을 수 있다.

In [6]:
mnist_test, info = tfds.load(name='fashion_mnist', with_info='true')
print(info)

tfds.core.DatasetInfo(
    name='fashion_mnist',
    full_name='fashion_mnist/3.0.1',
    description="""
    Fashion-MNIST is a dataset of Zalando's article images consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28x28 grayscale image, associated with a label from 10 classes.
    """,
    homepage='https://github.com/zalandoresearch/fashion-mnist',
    data_dir='/Users/chanhyeongkim/tensorflow_datasets/fashion_mnist/3.0.1',
    file_format=tfrecord,
    download_size=29.45 MiB,
    dataset_size=36.42 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=uint8),
        'label': ClassLabel(shape=(), dtype=int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{DBLP:journals/corr/abs-1708-07747,
  

### 케라스 모델에서 텐서플로 데이터셋 사용하기

2장에선 간단하게 패션 MNIST를 사용하는 코드는 다음과 같았다.

In [7]:
mnist = tf.keras.datasets.fashion_mnist
(X_train, y_trian), (X_test, y_test) = mnist.load_data()

텐서플로 데이터셋을 사용하는 방법도 매우 비슷하지만 조금 차이가 있다.

케라스 데이터셋은 ndarray 타입이다. 하지만 ***텐서플로 데이터셋은 Dataset 객체나 Tensor 타입을 반환*** 하기 떄문에 넘파이 배열로 바꾸려면 변환 작업이 약간 추가 된다

**** 

In [8]:
(X_train, y_train), (X_test, y_test) = tfds.as_numpy(tfds.load('fashion_mnist',
                                                    split=['train', 'test'],
                                                    batch_size=-1,
                                                    as_supervised=True))

1. tfds.load에 원하는 데이터셋 이름 지정
2. 이 데이터셋은 훈련,테스트 세트로 나눠져 있다는 걸 알고 있으므로 split 매개변수에 가져올 분할 세트 지정 가능
3. batch_size=-1로 지정하면 모든 데이터를 가져온다.
4. as_supervised=True로 지정하면 (입력, 레이블)로 구성된 튜플 반환
***
텐서플로 데이터셋에서 반환된 데이터셋은 케라스 데이터셋과 거의 포맷이 동일하다. 

한 가지 다른 점은 텐서플로 데이터셋은 (28, 28, 1) 크기를 반환하고 케라스 데이터셋은 (28, 28)크기 반환.

따라서 입력크기를 (28, 28, 1)로 지정해줘야 한다.

In [9]:
import tensorflow as tf
import tensorflow_datasets as tfds

(X_train, y_train), (X_test, y_test) = tfds.load('fashion_mnist',
                                                split=['train', 'test'],
                                                batch_size=-1,
                                                as_supervised=True)
X_train = tf.cast(X_train, tf.float32) / 255.0 # cast로 데이터타입 변경
X_test = tf.cast(X_test, tf.float32) / 255.0

model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28, 1)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 1s 527us/step - loss: 0.5292 - accuracy: 0.8125
Epoch 2/5
1875/1875 [==============================] - 1s 530us/step - loss: 0.4003 - accuracy: 0.8542
Epoch 3/5
1875/1875 [==============================] - 1s 523us/step - loss: 0.3684 - accuracy: 0.8651
Epoch 4/5
1875/1875 [==============================] - 1s 530us/step - loss: 0.3450 - accuracy: 0.8725
Epoch 5/5
1875/1875 [==============================] - 1s 528us/step - loss: 0.3335 - accuracy: 0.8768


In [10]:
import numpy as np
np.argmax(model.predict(X_train[:1]))

1/1 [==============================] - 0s 26ms/step


2

조금 더 복잡한 예제는 3장에서 다뤘던 말-사람 데이터셋이다. 이 데이터셋도 텐서플로 데이터셋에서 제공한다

In [11]:
import tensorflow as tf
import tensorflow_datasets as tfds

data = tfds.load('horses_or_humans', split='train', as_supervised=True)

train_batches = data.shuffle(100).batch(10)

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu', input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['acc'])
model.fit(train_batches, epochs=10)

Epoch 1/10
103/103 [==============================] - 11s 103ms/step - loss: 1.1915 - acc: 0.8773
Epoch 2/10
103/103 [==============================] - 10s 100ms/step - loss: 0.0902 - acc: 0.9718
Epoch 3/10
103/103 [==============================] - 10s 101ms/step - loss: 0.2223 - acc: 0.9270
Epoch 4/10
103/103 [==============================] - 10s 102ms/step - loss: 0.0372 - acc: 0.9903
Epoch 5/10
103/103 [==============================] - 11s 103ms/step - loss: 0.0012 - acc: 1.0000
Epoch 6/10
103/103 [==============================] - 11s 103ms/step - loss: 3.7826e-04 - acc: 1.0000
Epoch 7/10
103/103 [==============================] - 11s 103ms/step - loss: 6.8735e-05 - acc: 1.0000
Epoch 8/10
103/103 [==============================] - 11s 104ms/step - loss: 4.5185e-05 - acc: 1.0000
Epoch 9/10
103/103 [==============================] - 11s 104ms/step - loss: 3.1394e-05 - acc: 1.0000
Epoch 10/10
103/103 [==============================] - 11s 104ms/step - loss: 2.1619e-05 - acc: 1.0000

위에서 볼 수 있듯이 사용법이 아주 쉽다. 간단히 원하는 분할세트(여기에서는 train)을 지정해 load를 호출하고 모델 사용.

효율적인 훈련을 위해서 데이터를 섞고 배치(세트)를 구성했다.

말사람 데이터셋은 훈련-테스트로 나뉘어져 있으므로 훈련하는 동안 모델 검증을 원한다면 

텐서플로 데이터셋에서 별도의 검증 세트 로드 가능(밑에 코드)

In [12]:
val_data = tfds.load('horses_or_humans', split='test', as_supervised='true')

validation_batches = val_data.batch(32)

model.fit(train_batches, epochs=10, validation_data=validation_batches)

Epoch 1/10
103/103 [==============================] - 12s 112ms/step - loss: 1.4865e-05 - acc: 1.0000 - val_loss: 4.5882 - val_acc: 0.8555
Epoch 2/10
103/103 [==============================] - 11s 111ms/step - loss: 1.0292e-05 - acc: 1.0000 - val_loss: 4.5424 - val_acc: 0.8633
Epoch 3/10
103/103 [==============================] - 11s 111ms/step - loss: 8.3513e-06 - acc: 1.0000 - val_loss: 4.5498 - val_acc: 0.8672
Epoch 4/10
103/103 [==============================] - 11s 112ms/step - loss: 6.1173e-06 - acc: 1.0000 - val_loss: 4.6101 - val_acc: 0.8672
Epoch 5/10
103/103 [==============================] - 11s 112ms/step - loss: 4.9191e-06 - acc: 1.0000 - val_loss: 4.6222 - val_acc: 0.8633
Epoch 6/10
103/103 [==============================] - 12s 112ms/step - loss: 3.9941e-06 - acc: 1.0000 - val_loss: 4.6553 - val_acc: 0.8633
Epoch 7/10
103/103 [==============================] - 11s 111ms/step - loss: 3.2657e-06 - acc: 1.0000 - val_loss: 4.6786 - val_acc: 0.8633
Epoch 8/10
103/103 [=======

#### 특정 버전의 데이터셋 로드

텐서플로 데이터셋에 있는 모든 데이터셋은 **MAJOR.MINOR.PATCH** 버전 번호 시스텝을 사용한다

이 시스템은 다음처럼 관리된다.
- PATCH가 업데이트 되면 동일한 데이터가 반환되지만 내부 구성이 바뀌었을 수 있다. 이런 변화는 개발자에게 알려지지 않음
- MINOR가 업데이트 되면 기존 코드가 깨지지 않도록 데이터는 여전히 그대로지만 레코드마다 특성이 추가되었을 수 있다.
- 또한 특정 슬라이스의 데이터가 동일해야 하므로 레코드 순서가 바끼지 않는다. MINOR가 업데이트 되면 레코드 형태와 위치에 변화가 있을 수 있다. 따라서 특정 슬라이스는 다른 값을 반환할 수 있다.

다음처럼 버전을 명시적으로 지정 

In [13]:
data, info = tfds.load('horses_or_humans:3.0.0', with_info=True)

NonMathingCheckssumError 에러가 발생하면 수동으로 다운로드 하거나 tesorflow.org/datasets/overviiew#manual_download_if_download_fails 페이지 참고

### 데이터 증식을 위해 매핑 함수 사용

3장에서 훈련 데이터를 제공할 때 유용한 방법인 ImageDataGenerator를 사용한 이미지 증식 기법을 알아보았다.

이전처럼 디렉터리에서 이미지를 읽지 않기 떄문에 텐서플로 데이터셋을 사용할 때 이런 이미지 증식을 어떻게 수행하는지 궁금할 수 있다.

가장 좋은 방법은 데이터셋 객체에 매핑 함수를 사용하는 것이다.

In [14]:
data = tfds.load('horses_or_humans', split='train', as_supervised=True)
train_batches = data.shuffle(100).batch(10)

데이터셋을 변환해 매핑하려면 ***매핑함수**를 만들어야 한다. 이 함수는 평볌한 파이썬 함수이다.

예를 들어 augmentimages 함수를 만들어 다음과 같이 이미지 증식을 수행하겠다.

In [15]:
def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = (image/255)
    image = tf.image.random_flip_left_right(image)
    return image, label

이 함수를 다음과 같이 데이터에 매핑해 새로운 데이터셋 train을 만들 수 있다.

In [16]:
train = data.map(augmentimages)

그다음 data가 아니라 train에서 배치를 만든다

In [17]:
train_batches = train.shuffle(100).batch(32)

tf.image 라이브러리에는 이미지 증식에 사용할 수 있는 함수가 많다

#### 텐서플로 애드온 사용하기
텐서플로 에드온 라이브러리는 더 많은 함수를 제공한다. ImageDataGenerator에 있는 일부 기능(ex.rotate)은 텐서플로 에드온에서만 제공하기 떄문에 알아두는 것이 좋다.

In [18]:
#pip install tensorflow-addons

라이브러리 설치하면 매핑 함수에서 에드온 기능을 사용할 수 있다. 다음은 앞에서 만든 매핑 함수에 rotate 추가한 예이다.

In [19]:
import tensorflow_addons as tfa

def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = (image/255)
    image = tf.image.random_flip_left_right(image)
    image = tfa.image.rotate(image, 40, interpolation='NEAREST')
    return image, label

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(


### 사용자 정의 분할 사용하기

처음 1만개 데이터 불러옴(슬라이싱으로)

In [20]:
data = tfds.load('cats_vs_dogs', split='train[:10000]', as_supervised=True)

%를 사용해 데이터 불러오기(처음부터 20% 분량)

In [21]:
data = tfds.load('cats_vs_dogs', split='train[:20%]', as_supervised=True)

독특하게 두 개의 분할을 합칠 수도 있다. 마지막 1000개와 처음 1000개의 레코드를 합쳐서 훈련 데이터로 사용하고 싶다면 다음처럼 쓸 수 있다.

In [22]:
data = tfds.load('cats_vs_dogs', split='train[-1000:] + train[:1000]', as_supervised=True)

강아지-고양이 데이터셋은 훈련세트, 테스트세트, 검증세트 분할이 없지만 텐서플로 데이터셋을 사용해 간단히 세트를 분할할 수 있다.

데이터셋을 80%, 10%, 10% 비율로 나눈다 가정하면 다음과 같다

In [23]:
train_data = tfds.load('cats_vs_dogs', split='train[:80%]', as_supervised=True)

val_data = tfds.load('cats_vs_dogs', split='train[80:90%]', as_supervised=True)

test_data = tfds.load('cats_vs_dogs', split='train[-10%:]', as_supervised=True)

이렇게 얻은 세트는 기존과 동일한 방식으로 사용 가능

반환된 데이터셋은 길이 정보를 제공하지 않기 때문에 원본 세트를 올바르게 나누었는지 확인하는 것이 어렵다.

얼마나 많은 레코드가 분할세트에 포함되었는지 확인하려면 전체 세트를 순회하며 하나씩 카운트해야 한다.

In [24]:
train_length = [i for i, _ in enumerate(train_data)][-1] + 1
print(train_length)

18610


tf.data.experimental.cardinality 함수를 사용해 카운트 가능

tf.int64 타입의 텐서를 반환하므로 다음처럼 numpy() 메서드로 넘파이 스칼라 값으로 바꾸어 출력 가능

In [25]:
tf.data.experimental.cardinality(train_data).numpy()

18610

fashion_mnist 처럼 미리 분할된 데이터셋은 with_info=True로 지정해 분할세트 크기 확인 가능(위에 있음)

### TFRecord 이해하기
텐서플로 데이터셋은 데이터를 다운로드해 디스크에 캐싱한다. 따라서 사용할 때마다 데이터를 다운로드하지 않는다.

텐서플로 데이터셋은 캐싱을 위해 TFRecord 포맷을 사용한다. 이는 텐서플로에서 대용량의 데이터를 저장하고 추출할 때 선호하는 포맷이다.

파일 구조는 매우 단순하며 성능을 위해 순차적으로 읽는다.

디스크에 저장된 파일은 매우 간단하며 각 레코드는 레코드의 길이를 나타내는 정수, 이 정수의 CRC(순환 중복 검사) 데이터의 바이트 배열, 바이트 배열의 CRC로 구성.

레코드가 연결되어 파일을 구성하고 대규모 데이터셋일 경우 샤딩(sharding) 된다.
- 샤딩은 각 DB 서버에서 데이터를 분할하여 저장하는 방식이다

MNIST 데이터셋을 다운로드하고 정보를 출력해 간단한 예를 살펴보자

In [26]:
data, info = tfds.load('mnist', with_info=True)
print(info)

tfds.core.DatasetInfo(
    name='mnist',
    full_name='mnist/3.0.1',
    description="""
    The MNIST database of handwritten digits.
    """,
    homepage='http://yann.lecun.com/exdb/mnist/',
    data_dir='/Users/chanhyeongkim/tensorflow_datasets/mnist/3.0.1',
    file_format=tfrecord,
    download_size=11.06 MiB,
    dataset_size=21.00 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=uint8),
        'label': ClassLabel(shape=(), dtype=int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{lecun2010mnist,
      title={MNIST handwritten digit database},
      author={LeCun, Yann and Cortes, Corinna and Burges, CJ},
      journal={ATT Labs [Online]. Available: http://yann.lecun.com/exdb/mnist},
      volume={2},
      year={2010}
    }""",
)

features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=uint8),
        'label': ClassLabel(shape=(), dtype=int64, num_classes=10),
    })
    
data_dir='/Users/chanhyeongkim/tensorflow_datasets/mnist/3.0.1.incomplete7GQAIK'
  

다음처럼 원시 레코드를 TFRecord로 로드할 수 있다

In [27]:
import os

file_name = os.path.join(os.path.expanduser('~') +
                         '/tensorflow_datasets/mnist/3.0.1/mnist-test.tfrecord-00000-of-00001')
raw_dataset = tf.data.TFRecordDataset(file_name)

for raw_record in raw_dataset.take(1): # 원시레코드 내용 출력
    print(repr(raw_record))

<tf.Tensor: shape=(), dtype=string, numpy=b"\n\x85\x03\n\xf2\x02\n\x05image\x12\xe8\x02\n\xe5\x02\n\xe2\x02\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x1c\x00\x00\x00\x1c\x08\x00\x00\x00\x00Wf\x80H\x00\x00\x01)IDAT(\x91\xc5\xd2\xbdK\xc3P\x14\x05\xf0S(v\x13)\x04,.\x82\xc5Aq\xac\xedb\x1d\xdc\n.\x12\x87n\x0e\x82\x93\x7f@Q\xb2\x08\xba\tbQ0.\xe2\xe2\xd4\xb1\xa2h\x9c\x82\xba\x8a(\nq\xf0\x83Fh\x95\n6\x88\xe7R\x87\x88\xf9\xa8Y\xf5\x0e\x8f\xc7\xfd\xdd\x0b\x87\xc7\x03\xfe\xbeb\x9d\xadT\x927Q\xe3\xe9\x07:\xab\xbf\xf4\xf3\xcf\xf6\x8a\xd9\x14\xd29\xea\xb0\x1eKH\xde\xab\xea%\xaba\x1b=\xa4P/\xf5\x02\xd7\\\x07\x00\xc4=,L\xc0,>\x01@2\xf6\x12\xde\x9c\xde[t/\xb3\x0e\x87\xa2\xe2\xc2\xe0A<\xca\xb26\xd5(\x1b\xa9\xd3\xe8\x0e\xf5\x86\x17\xceE\xdarV\xae\xb7_\xf3AR\r!I\xf7(\x06m\xaaE\xbb\xb6\xac\r*\x9b$e<\xb8\xd7\xa2\x0e\x00\xd0l\x92\xb2\xd5\x15\xcc\xae'\x00\xf4m\x08O'+\xc2y\x9f\x8d\xc9\x15\x80\xfe\x99[q\x962@CN|i\xf7\xa9!=\xd7 \xab\x19\x00\xc8\xd6\xb8\xeb\xa1\xf0\xd8l\xca\xfb]\xee\xfb]*\x9fV\xe1\x07\xb7\xc

**체크섬** 과 레코드 내용이 포함된 긴 문자열 출력

이 데이터셋의 특성을 이미 알고 있기 때문에 **특성 디스크립션** 을 만들어 데이터를 파싱할 수 있다.

데이터를 파싱하는 코드는 다음과 같다.

In [28]:
# 특성 디스크립션을 만든다
feature_description = {
    'image': tf.io.FixedLenFeature([], dtype=tf.string),
    'label': tf.io.FixedLenFeature([], dtype=tf.int64)
}

def _parse_func(example_proto):
    # 위에서 만든 딕셔너리로 입력을 파싱한다.
    return tf.io.parse_single_example(example_proto, feature_description)

parsed_dataset = raw_dataset.map(_parse_func)
for parsed_record in parsed_dataset.take(1):
    print((parsed_record))

{'image': <tf.Tensor: shape=(), dtype=string, numpy=b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x1c\x00\x00\x00\x1c\x08\x00\x00\x00\x00Wf\x80H\x00\x00\x01)IDAT(\x91\xc5\xd2\xbdK\xc3P\x14\x05\xf0S(v\x13)\x04,.\x82\xc5Aq\xac\xedb\x1d\xdc\n.\x12\x87n\x0e\x82\x93\x7f@Q\xb2\x08\xba\tbQ0.\xe2\xe2\xd4\xb1\xa2h\x9c\x82\xba\x8a(\nq\xf0\x83Fh\x95\n6\x88\xe7R\x87\x88\xf9\xa8Y\xf5\x0e\x8f\xc7\xfd\xdd\x0b\x87\xc7\x03\xfe\xbeb\x9d\xadT\x927Q\xe3\xe9\x07:\xab\xbf\xf4\xf3\xcf\xf6\x8a\xd9\x14\xd29\xea\xb0\x1eKH\xde\xab\xea%\xaba\x1b=\xa4P/\xf5\x02\xd7\\\x07\x00\xc4=,L\xc0,>\x01@2\xf6\x12\xde\x9c\xde[t/\xb3\x0e\x87\xa2\xe2\xc2\xe0A<\xca\xb26\xd5(\x1b\xa9\xd3\xe8\x0e\xf5\x86\x17\xceE\xdarV\xae\xb7_\xf3AR\r!I\xf7(\x06m\xaaE\xbb\xb6\xac\r*\x9b$e<\xb8\xd7\xa2\x0e\x00\xd0l\x92\xb2\xd5\x15\xcc\xae'\x00\xf4m\x08O'+\xc2y\x9f\x8d\xc9\x15\x80\xfe\x99[q\x962@CN|i\xf7\xa9!=\xd7 \xab\x19\x00\xc8\xd6\xb8\xeb\xa1\xf0\xd8l\xca\xfb]\xee\xfb]*\x9fV\xe1\x07\xb7\xc9\x8b55\xe7M\xef\xb0\x04\xc0\xfd&\x89\x01<\xbe\xf9\x0

##### 참고
parsing은 구문 분석이라고 합니다. 문장이 이루고 있는 구성 성분을 분해하고 분해된 성분의 위계 관계를 분석하여 구조를 결정하는 것입니다. 

즉 데이터를 분해 분석하여 원하는 형태로 조립하고 다시 빼내는 프로그램을 말합니다. 웹상에서 주어진 정보를 내가 원하는 형태로 가공하여 서버에서 불러들이는 것입니다.

파싱된 결과는 좀 더 알아보기 쉽다. 무엇보다도 이미지가 Tensor이고 PNG 형식임을 확인할 수 있다.(numpy=b"\x89PNG\.. , 첫줄)

PNG는 압축 이미지 포맷으로 헤더는 IHDR로 시작하고 데이터는 IDAT로 시작하며 IEND로 끝난다.(파싱된 결과 위에 보면 있음)

이제 원시 TFReocord 파일을 읽어서 Pillow 같은 라이브러리를 사용해 PNG 이미지로 디코딩 할 수 있다.

### 텐서플로에서 데이터 관리를 위한 ETL 프로세스
ETL은 규모와 상관없이 텐서플로의 훈련에 사용되는 핵심 패턴이다. 

***
ETL 프로세스의 
- **추출단계**는 다른 곳에 저장되어 있는 원시 데이터를 가져와 변환을 위해 준비하는 단계이다.

- **변환단계** 는 훈련에 적합하도록 또는 훈련이 잘되도록 데이터를 조작하는 단계이다. 예를 들어 이미지증식, 특성열매핑, 또는 데이터에 적용하는 다른 변환 로직 등.

- **로드(적재)단계** 는 훈련을 위해 신경망에 데이터를 로드하는 단계이다.

다음은 말-사람 데이터셋으로 분류기를 훈련하는 전체코드이다. 추출, 변환, 로드 단계를 구분할 수 있도록 주석을 추가함

#### 말-사람 데이터 훈련 전체 소스코드

In [29]:
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_addons as tfa

# 모델 정의 #
model2 = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu', input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model2.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

# 추출 단계 #
data = tfds.load('horses_or_humans', split='train', as_supervised=True)

val_data = tfds.load('horses_or_humans', split='test', as_supervised=True)


# 변환 단계 #

def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = (image/255)
    image = tf.image.random_flip_left_right(image)
    image = tfa.image.rotate(image, 40, interpolation='NEAREST')
    return image, label

train = data.map(augmentimages)
train_batches = train.shuffle(100).batch(32)
val_batches = val_data.batch(32)

# 로드 단계 #
history = model2.fit(train_batches, epochs=10, validation_data=val_batches)

Epoch 1/10
33/33 [==============================] - 11s 318ms/step - loss: 0.4940 - acc: 0.7527 - val_loss: 255.7508 - val_acc: 0.5977
Epoch 2/10
33/33 [==============================] - 10s 312ms/step - loss: 0.1326 - acc: 0.9494 - val_loss: 290.4411 - val_acc: 0.5391
Epoch 3/10
33/33 [==============================] - 10s 311ms/step - loss: 0.0999 - acc: 0.9630 - val_loss: 244.2785 - val_acc: 0.5469
Epoch 4/10
33/33 [==============================] - 10s 311ms/step - loss: 0.0272 - acc: 0.9912 - val_loss: 336.0301 - val_acc: 0.4648
Epoch 5/10
33/33 [==============================] - 10s 313ms/step - loss: 0.0318 - acc: 0.9893 - val_loss: 370.6453 - val_acc: 0.4570
Epoch 6/10
33/33 [==============================] - 10s 312ms/step - loss: 0.1828 - acc: 0.9367 - val_loss: 321.5753 - val_acc: 0.5664
Epoch 7/10
33/33 [==============================] - 10s 309ms/step - loss: 0.0649 - acc: 0.9796 - val_loss: 361.9042 - val_acc: 0.4258
Epoch 8/10
33/33 [==============================] - 10s

이런 프로세스를 사용하며 데이터 파이프라인이 데이터나 모델 구조의 변화에 덜 민감하도록 만들 수 있다.

- ***텐서플로 데이터셋을 이용해 데이터를 추출하는 구조는 데이터의 크기와는 상관없이 동일하다***

- 변환을 위한 tf.data API도 일관성 있어 데이터 소스와는 상관없이 비슷한 변환 적용 가능

- 물론 변환이 되고 난 후 데이터 로딩 단계도 하나의 cpu나 하나의 gpu, gpu 클러스터 또는 tpu 포드에서 훈련하는지와는 상관없이 동일하다. 하지만 데이터를 로드하는 단계가 훈련 속도에 큰 영향을 미칠 수는 있다.

#### 로드 단계 최적화 하기

CPU가 작업을 준비하는 동안 GPU/TPU는 유휴상태이다(아무것도 안함).

그리고 GPU/TPU에서 훈련을 하는데, 이떄는 CPU가 유휴상태이다.

***

이에 대해 데이터 준비와 훈련을 병렬로 수행하는 것이 논리적인 해결책이다.
이런 과정을 **파이프라이닝**이라고 한다.
- 첫번쨰 배치는 CPU가 준비하고, 두번쨰부터 GPU/TPU가 훈련하는 동안 CPU는 다음배치 준비를 한다.

케라스의 패션 MNIST 같은 간단한 데이터셋에서 텐서프롤 데이터셋 버전으로 바꿀 떄 훈련 전에 배치를 만들어야 한다.

이는 데이터셋이 얼마나 큰지와는 상관없이 파이프라이닝을 사용하기 떄문이다. 따라서 일관된 ETL 패턴을 계속 사용할 수 있다.


#### 훈련속도 향상을 위해 ETL 병렬화하기

In [30]:
train_data, info = tfds.load('cats_vs_dogs', split='train', with_info=True)

In [31]:
print(info)

tfds.core.DatasetInfo(
    name='cats_vs_dogs',
    full_name='cats_vs_dogs/4.0.1',
    description="""
    A large set of images of cats and dogs. There are 1738 corrupted images that are dropped.
    """,
    homepage='https://www.microsoft.com/en-us/download/details.aspx?id=54765',
    data_dir='/Users/chanhyeongkim/tensorflow_datasets/cats_vs_dogs/4.0.1',
    file_format=tfrecord,
    download_size=786.67 MiB,
    dataset_size=1.04 GiB,
    features=FeaturesDict({
        'image': Image(shape=(None, None, 3), dtype=uint8),
        'image/filename': Text(shape=(), dtype=string),
        'label': ClassLabel(shape=(), dtype=int64, num_classes=2),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'train': <SplitInfo num_examples=23262, num_shards=16>,
    },
    citation="""@Inproceedings (Conference){asirra-a-captcha-that-exploits-interest-aligned-manual-image-categorization,
    author = {Elson, Jeremy and Douceur, John (JD) and Howell,

TFRecord를 사용하고 싶다면 다운로드된 원시 파일을 읽어야 한다. 데이터셋이 크다면 여러개의 파일에 나눠져있다.(버전4.0.0의 경우 파일 8개 )

tf.data.Dataset.list_files를 사용해 로드할 파일 목록 만듦

In [32]:
file_pattern = os.path.join(
    os.path.expanduser('~') +
    '/tensorflow_datasets/cats_vs_dogs/4.0.1/cats_vs_dogs-train.tfrecord*'
)
files = tf.data.Dataset.list_files(file_pattern)

파일 목록을 얻으면 다음처럼 files.interleave를 사용해 데이터셋을 로드한다.

In [33]:
train_dataset = files.interleave(
    tf.data.TFRecordDataset,
    cycle_length=4,
    num_parallel_calls=tf.data.experimental.AUTOTUNE
)

새롭게 등장한 개념이 몇 가지 있다.

- **cycle_length** 매개변수는 동시에 전처리할 입력 원소 개수를 지정한다. 4로 지정했기 때문에 이 프로세스는 동시에 4개의 레코드를 처리한다. 이값을 지정하지 않으면 사용 가능한 CPU 코어 개수를 사용한다

- **num_parallel_calls** 매개변수는 병렬 실행횟수를 지정한다. 여기서처럼 **tf.data.experimental.AUTOTUNE** 로 지정하면 CPU 개수에 따라 동적으로 설정되기 때문에 코드 이식성이 좋아진다.
**cycle_length** 와 **num_parallel_calls** 를 같이 사용하면 병렬화를 최대로 활용 가능하다. 

예를 들어 자동으로 설정된 **num_parallel_calls** 값이 6이고, **cycle_length** 가 4이면 6개의 스레드가 각각 4개의 레코드를 동시에 로딩한다


추출단계 병렬화에 이허 **변환단계 병렬화** 에 대해 알아보겠다. 먼저 원시 TFRecord 파일을 로드하고 적절한 형태로 바꾸는 매핑 함수를 만든다. 

예를 들어 JPEG 이미지를 디코딩해 이미지 버퍼에 저장한다.

In [34]:
def read_tfrecord(serialized_example):
    feature_description={
        'image':tf.io.FixedLenFeature((), tf.string, ""),
        'label':tf.io.FixedLenFeature((), tf.int64, -1)
    }
    example = tf.io.parse_single_example(
        serialized_example, feature_description
    )
    
    image = tf.io.decode_jpeg(example['image'], channels=3)
    image = tf.cast(image, tf.float32)
    image = image / 255
    image = tf.image.resize(image, (300, 300))
    return image, example['label']

여기서 볼 수 있듯이 일반적인 매핑함수는 병렬 작업을 위해 특별히 처리하는 것이 없다.

병렬화는 다음처럼 매핑함수를 호출할 때 수행된다.

In [35]:
import multiprocessing

cores = multiprocessing.cpu_count()
print(cores)
train_dataset = train_dataset.map(read_tfrecord, num_parallel_calls=cores)
train_dataset = train_dataset.cache()

10


자동설정을 원치 않으면  multiprocessing 라이브러리를 사용해 CPU 개수를 카운트해준다. 그다음 매핑 함수를 호출할 때 병렬실행횟수에 이 값을 전달한다. 간단하다

cache 메서드는 메모리에 데이터셋을 캐싱한다.

램이 충분하다면 속도 향상에 아주 좋다. 강아지-고양이 데이터셋으로 콜랩에서 실행하면 램이 부족해서 오류 발생.

로딩과 훈련도 병렬화 할 수 있다. 데이터를 섞고 배치를 만드는 것은 물론 다음 코드처럼 사용 가능한 CPU 코어 개수를 바탕으로 데이터를 **프리페치** 할 수 있다.

In [36]:
train_dataset = train_dataset.shuffle(1024).batch(32)
train_dataset = train_dataset.prefetch(tf.data.experimental.AUTOTUNE)

훈련세트 병렬화 준비를 마치면 이전처럼 모델을 훈련한다.

In [ ]:

model3 = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu', input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model3.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

model3.fit(train_dataset, epochs=10, verbose=1)

Epoch 1/10
    718/Unknown - 212s 295ms/step - loss: 0.6257 - acc: 0.6190

왤케 오래 걸리냐?..

맥으론 오래 걸려서 클라우드를 이용하는 코랩으로 돌려봄

코랩에서도 안 된다. 용량이 너무 큰가 보다