<a href="https://colab.research.google.com/github/chanhyeong00/machine_learning_study/blob/main/%08Pytorch/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 단순 선형 회귀: 넘파이

In [ ]:
import numpy as np

x = np.array(
    [[1], [2], [3], [4], [5], [6], [7], [8], [9], [10],
    [11], [12], [13], [14], [15], [16], [17], [18], [19], [20],
    [21], [22], [23], [24], [25], [26], [27], [28], [29], [30]]
)
y = np.array(
    [[0.94], [1.98], [2.88], [3.92], [3.96], [4.55], [5.64], [6.3], [7.44], [9.1],
    [8.46], [9.5], [10.67], [11.16], [14], [11.83], [14.4], [14.25], [16.2], [16.32],
    [17.46], [19.8], [18], [21.34], [22], [22.5], [24.57], [26.04], [21.6], [28.8]]
)

In [ ]:
weight = 0.0
bias = 0.0
learning_rate = 0.005

In [ ]:
for epoch in range(10000):
    y_hat = weight * x + bias # 가설(hypothesis)

    # mean()을 사용해 하나로 묶음(batch 적용)
    # -> 여기서는 데이터 크기인 30이 된다.(30 * 10,000이지만 30개를 묶어서 10,000번만)

    cost = ((y - y_hat) ** 2).mean() # 손실(loss)

    # W_i+1 = W_i - a(lr) * E[(Y_hat - y_i) * x] -> 가중치 함수(책 68p)
    weight = weight - learning_rate * ((y_hat - y) * x).mean() # 가중치

    # 이건 책 68p에서 bias에 대해서 편미분 진행
    bias = bias - learning_rate * (y_hat - y).mean() # b(편향)

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Weight : {weight:.3f}, Bias : {bias:.3f}, Cost : {cost:.3f}")

Epoch : 1000, Weight : 0.872, Bias : -0.290, Cost : 1.377
Epoch : 2000, Weight : 0.877, Bias : -0.391, Cost : 1.373
Epoch : 3000, Weight : 0.878, Bias : -0.422, Cost : 1.372
Epoch : 4000, Weight : 0.879, Bias : -0.432, Cost : 1.372
Epoch : 5000, Weight : 0.879, Bias : -0.435, Cost : 1.372
Epoch : 6000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 7000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 8000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 9000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 10000, Weight : 0.879, Bias : -0.436, Cost : 1.372


위의 설정된 옵션에서 6,000번 정도 학습했을 때 더이상 오차가 감소하지 않는다.

초깃값 설정 등 학습에 영향을 많이 끼친다.

그러므로 적절하지 않은 초깃값을 할당했을 때 하이퍼파라미터 튜닝을 진행하고 이를 통해 원할한 학습 진행 가능

### 단순 선형 회귀: 파이토치

In [ ]:
import torch
from torch import optim

In [ ]:
x = torch.FloatTensor([
    [1], [2], [3], [4], [5], [6], [7], [8], [9], [10],
    [11], [12], [13], [14], [15], [16], [17], [18], [19], [20],
    [21], [22], [23], [24], [25], [26], [27], [28], [29], [30]
])
y = torch.FloatTensor([
    [0.94], [1.98], [2.88], [3.92], [3.96], [4.55], [5.64], [6.3], [7.44], [9.1],
    [8.46], [9.5], [10.67], [11.16], [14], [11.83], [14.4], [14.25], [16.2], [16.32],
    [17.46], [19.8], [18], [21.34], [22], [22.5], [24.57], [26.04], [21.6], [28.8]
])

**하이퍼 파라미터 초기화**

In [ ]:
weight = torch.zeros(1, requires_grad=True)
bias = torch.zeros(1, requires_grad=True)
learning_rate = 0.001

In [ ]:
optimizer = optim.SGD([weight, bias], lr=learning_rate)

In [ ]:
for epoch in range(10000):
    hypothesis = weight * x + bias
    cost = torch.mean((hypothesis - y) ** 2)

    optimizer.zero_grad() # optimizer 변수에 포함시킨 매개변수들의 기울기를 0으로 초기화
    # weight += x 로 축적되어 저장됨(중복연산 방지)

    cost.backward() # 역전파(back propagation) 수행. 매개변수들의 기울기가 새로 계산된다
    optimizer.step() # 최적화 함수에 반영. lr 값을 반영한 확률적 경사하강법 연산이 적용된다.

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Weight : {weight.item():.3f}, Bias : {bias.item():.3f}, Cost : {cost:.3f}")

Epoch : 1000, Weight : 0.864, Bias : -0.138, Cost : 1.393
Epoch : 2000, Weight : 0.870, Bias : -0.251, Cost : 1.380
Epoch : 3000, Weight : 0.873, Bias : -0.321, Cost : 1.375
Epoch : 4000, Weight : 0.875, Bias : -0.364, Cost : 1.373
Epoch : 5000, Weight : 0.877, Bias : -0.391, Cost : 1.373
Epoch : 6000, Weight : 0.878, Bias : -0.408, Cost : 1.372
Epoch : 7000, Weight : 0.878, Bias : -0.419, Cost : 1.372
Epoch : 8000, Weight : 0.878, Bias : -0.425, Cost : 1.372
Epoch : 9000, Weight : 0.879, Bias : -0.429, Cost : 1.372
Epoch : 10000, Weight : 0.879, Bias : -0.432, Cost : 1.372


넘파이와 동일하게 수렴되는 것을 볼 수 있다.

학습률은 0.001로 기존 경사 하강법보다 낮은 학습률을 사용하지만,

SGD(Stochastic Gradient Descent), 확률적경사하강법을 활용해 더 빠른 속도로 최적의 가중치와 편향을 찾았다.

### Zero_grad(), cost.backward(), optimizer.step() 알아보기

In [ ]:
import torch
from torch import optim


x = torch.FloatTensor([
    [1], [2], [3], [4], [5], [6], [7], [8], [9], [10],
    [11], [12], [13], [14], [15], [16], [17], [18], [19], [20],
    [21], [22], [23], [24], [25], [26], [27], [28], [29], [30]
])
y = torch.FloatTensor([
    [0.94], [1.98], [2.88], [3.92], [3.96], [4.55], [5.64], [6.3], [7.44], [9.1],
    [8.46], [9.5], [10.67], [11.16], [14], [11.83], [14.4], [14.25], [16.2], [16.32],
    [17.46], [19.8], [18], [21.34], [22], [22.5], [24.57], [26.04], [21.6], [28.8]
])

weight = torch.zeros(1, requires_grad=True)
bias = torch.zeros(1, requires_grad=True)
learning_rate = 0.001

optimizer = optim.SGD([weight, bias], lr=learning_rate)

for epoch in range(10000):
    hypothesis = weight * x + bias
    cost = torch.mean((hypothesis - y) ** 2)

    print(f"Epoch : {epoch+1:4d}") # 토치 텐서에는 grad가 있다.
    print(f"Step [1] : Gradient : {weight.grad}, Weight : {weight.item():.5f}")

    optimizer.zero_grad() # 옵티마이저 기울기 초기화
    print(f"Step [2] : Gradient : {weight.grad}, Weight : {weight.item():.5f}")

    cost.backward() # 역전파 수행해서 기울기 계산(weight에는 반영되지 않음)
    print(f"Step [3] : Gradient : {weight.grad}, Weight : {weight.item():.5f}")

    optimizer.step() # 위에서 계산한 weight 변수에 반영한다.
    print(f"Step [4] : Gradient : {weight.grad}, Weight : {weight.item():.5f}")

    if epoch == 3:
        break

Epoch :    1
Step [1] : Gradient : None, Weight : 0.00000
Step [2] : Gradient : None, Weight : 0.00000
Step [3] : Gradient : tensor([-540.4854]), Weight : 0.00000
Step [4] : Gradient : tensor([-540.4854]), Weight : 0.54049
Epoch :    2
Step [1] : Gradient : tensor([-540.4854]), Weight : 0.54049
Step [2] : Gradient : None, Weight : 0.54049
Step [3] : Gradient : tensor([-198.9818]), Weight : 0.54049
Step [4] : Gradient : tensor([-198.9818]), Weight : 0.73947
Epoch :    3
Step [1] : Gradient : tensor([-198.9818]), Weight : 0.73947
Step [2] : Gradient : None, Weight : 0.73947
Step [3] : Gradient : tensor([-73.2604]), Weight : 0.73947
Step [4] : Gradient : tensor([-73.2604]), Weight : 0.81273
Epoch :    4
Step [1] : Gradient : tensor([-73.2604]), Weight : 0.81273
Step [2] : Gradient : None, Weight : 0.81273
Step [3] : Gradient : tensor([-26.9772]), Weight : 0.81273
Step [4] : Gradient : tensor([-26.9772]), Weight : 0.83970


### 신경망 패키지

In [ ]:
import torch
from torch import nn
from torch import optim

In [ ]:
x = torch.FloatTensor([
    [1], [2], [3], [4], [5], [6], [7], [8], [9], [10],
    [11], [12], [13], [14], [15], [16], [17], [18], [19], [20],
    [21], [22], [23], [24], [25], [26], [27], [28], [29], [30]
])
y = torch.FloatTensor([
    [0.94], [1.98], [2.88], [3.92], [3.96], [4.55], [5.64], [6.3], [7.44], [9.1],
    [8.46], [9.5], [10.67], [11.16], [14], [11.83], [14.4], [14.25], [16.2], [16.32],
    [17.46], [19.8], [18], [21.34], [22], [22.5], [24.57], [26.04], [21.6], [28.8]
])

In [ ]:
model = nn.Linear(1, 1)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [ ]:
for epoch in range(10000):
    output = model(x)
    cost = criterion(output, y)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.8707]], requires_grad=True), Parameter containing:
tensor([-0.2684], requires_grad=True)], Cost : 1.379
Epoch : 2000, Model : [Parameter containing:
tensor([[0.8738]], requires_grad=True), Parameter containing:
tensor([-0.3317], requires_grad=True)], Cost : 1.375
Epoch : 3000, Model : [Parameter containing:
tensor([[0.8757]], requires_grad=True), Parameter containing:
tensor([-0.3711], requires_grad=True)], Cost : 1.373
Epoch : 4000, Model : [Parameter containing:
tensor([[0.8769]], requires_grad=True), Parameter containing:
tensor([-0.3956], requires_grad=True)], Cost : 1.373
Epoch : 5000, Model : [Parameter containing:
tensor([[0.8777]], requires_grad=True), Parameter containing:
tensor([-0.4108], requires_grad=True)], Cost : 1.372
Epoch : 6000, Model : [Parameter containing:
tensor([[0.8781]], requires_grad=True), Parameter containing:
tensor([-0.4203], requires_grad=True)], Cost : 1.372
Epoch : 7000, Model : [Parameter contain

### 다중 선형 회귀

In [ ]:
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader


train_x = torch.FloatTensor([
    [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]
]) # (n,2), 독립변수 두개
train_y = torch.FloatTensor([
    [0.1, 1.5], [1, 2.8], [1.9, 4.1], [2.8, 5.4], [3.7, 6.7], [4.6, 8]
]) # 다중회귀를 위해 (n,2) 형태로 입력

TensorDataset은 기본 Dataset 클래스를 상속받아 재정의된 클래스이다.

In [ ]:
train_dataset = TensorDataset(train_x, train_y)
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True, drop_last=True)
# 배치 크기 조절, 셔플(데이터 순서 변경),
# drop_last: 배치제거(배치 크기에 맞지 않는 배치를 제거) -> 불완전한 배치를 사용할지 말지를 정함

In [ ]:
model = nn.Linear(2, 2, bias=True)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [ ]:
for epoch in range(20000):
    cost = 0.0

    for batch in train_dataloader:
        x, y = batch # 배치
        output = model(x) # 예측

        loss = criterion(output, y)

        optimizer.zero_grad() # 기울기 초기화
        loss.backward() # 역전파 수행(기울기 계산)
        optimizer.step() # 옵티마이저에 weight 반영

        cost += loss

    cost = cost / len(train_dataloader) # 손실

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.5812, 0.2188],
        [0.8209, 0.3467]], requires_grad=True), Parameter containing:
tensor([-0.5974,  0.4114], requires_grad=True)], Cost : 0.047
Epoch : 2000, Model : [Parameter containing:
tensor([[0.6828, 0.1662],
        [0.9554, 0.2770]], requires_grad=True), Parameter containing:
tensor([-0.7515,  0.2072], requires_grad=True)], Cost : 0.012
Epoch : 3000, Model : [Parameter containing:
tensor([[0.7345, 0.1394],
        [1.0240, 0.2415]], requires_grad=True), Parameter containing:
tensor([-0.8301,  0.1032], requires_grad=True)], Cost : 0.003
Epoch : 4000, Model : [Parameter containing:
tensor([[0.7609, 0.1258],
        [1.0589, 0.2235]], requires_grad=True), Parameter containing:
tensor([-0.8701,  0.0503], requires_grad=True)], Cost : 0.001
Epoch : 5000, Model : [Parameter containing:
tensor([[0.7744, 0.1189],
        [1.0767, 0.2143]], requires_grad=True), Parameter containing:
tensor([-0.8905,  0.0233], requires_grad=True)]

**편향 제거**

In [ ]:
model = nn.Linear(2, 2, bias=False)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [ ]:
for epoch in range(20000):
    cost = 0.0

    for batch in train_dataloader:
        x, y = batch
        output = model(x)

        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        cost += loss

    cost = cost / len(train_dataloader)

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.4822, 0.1852],
        [0.9144, 0.3502]], requires_grad=True)], Cost : 0.097
Epoch : 2000, Model : [Parameter containing:
tensor([[ 0.7321, -0.0170],
        [ 0.9524,  0.3194]], requires_grad=True)], Cost : 0.061
Epoch : 3000, Model : [Parameter containing:
tensor([[ 0.9306, -0.1778],
        [ 0.9827,  0.2948]], requires_grad=True)], Cost : 0.038
Epoch : 4000, Model : [Parameter containing:
tensor([[ 1.0886, -0.3055],
        [ 1.0068,  0.2754]], requires_grad=True)], Cost : 0.024
Epoch : 5000, Model : [Parameter containing:
tensor([[ 1.2141, -0.4070],
        [ 1.0259,  0.2599]], requires_grad=True)], Cost : 0.015
Epoch : 6000, Model : [Parameter containing:
tensor([[ 1.3138, -0.4877],
        [ 1.0411,  0.2476]], requires_grad=True)], Cost : 0.010
Epoch : 7000, Model : [Parameter containing:
tensor([[ 1.3930, -0.5518],
        [ 1.0532,  0.2378]], requires_grad=True)], Cost : 0.006
Epoch : 8000, Model : [Parameter containing:
